# Creating namespace for dc-gREST
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: dc-grest
---
# Creating a deployment for grpc-workers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-deployment
  namespace: ns2               # changing namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-worker
  template:
    metadata:
      labels:
        app: grpc-worker
    spec:
      containers:
      - name: grpc
        image: daitya96/dc-grest-grpc-server:0.0.1
        resources:
          requests:
            memory: "100Mi"
            cpu: "300m"
          limits:
            memory: "200Mi"
            cpu: "500m"
        ports:
        - containerPort: 8097
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-svc
  namespace: ns2                # changing namespace
spec:
  selector:
    app: grpc-worker
  ports:
  - port: 8097        # host port
    targetPort: 8097  # container port
  type: LoadBalancer
---

