// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: matrix.proto

package io.github.stubs.matrix;

public final class Matrix {
  private Matrix() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface multiplyBlockRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:multiplyBlockRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated sfixed64 row = 1;</code>
     */
    java.util.List<java.lang.Long> getRowList();
    /**
     * <code>repeated sfixed64 row = 1;</code>
     */
    int getRowCount();
    /**
     * <code>repeated sfixed64 row = 1;</code>
     */
    long getRow(int index);

    /**
     * <code>repeated sfixed64 column = 2;</code>
     */
    java.util.List<java.lang.Long> getColumnList();
    /**
     * <code>repeated sfixed64 column = 2;</code>
     */
    int getColumnCount();
    /**
     * <code>repeated sfixed64 column = 2;</code>
     */
    long getColumn(int index);

    /**
     * <code>int32 rowId = 3;</code>
     */
    int getRowId();

    /**
     * <code>int32 columnId = 4;</code>
     */
    int getColumnId();
  }
  /**
   * Protobuf type {@code multiplyBlockRequest}
   */
  public  static final class multiplyBlockRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:multiplyBlockRequest)
      multiplyBlockRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use multiplyBlockRequest.newBuilder() to construct.
    private multiplyBlockRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private multiplyBlockRequest() {
      row_ = java.util.Collections.emptyList();
      column_ = java.util.Collections.emptyList();
      rowId_ = 0;
      columnId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private multiplyBlockRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                row_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              row_.add(input.readSFixed64());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                row_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                row_.add(input.readSFixed64());
              }
              input.popLimit(limit);
              break;
            }
            case 17: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                column_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000002;
              }
              column_.add(input.readSFixed64());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                column_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                column_.add(input.readSFixed64());
              }
              input.popLimit(limit);
              break;
            }
            case 24: {

              rowId_ = input.readInt32();
              break;
            }
            case 32: {

              columnId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          row_ = java.util.Collections.unmodifiableList(row_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          column_ = java.util.Collections.unmodifiableList(column_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.stubs.matrix.Matrix.internal_static_multiplyBlockRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.stubs.matrix.Matrix.internal_static_multiplyBlockRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.stubs.matrix.Matrix.multiplyBlockRequest.class, io.github.stubs.matrix.Matrix.multiplyBlockRequest.Builder.class);
    }

    private int bitField0_;
    public static final int ROW_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Long> row_;
    /**
     * <code>repeated sfixed64 row = 1;</code>
     */
    public java.util.List<java.lang.Long>
        getRowList() {
      return row_;
    }
    /**
     * <code>repeated sfixed64 row = 1;</code>
     */
    public int getRowCount() {
      return row_.size();
    }
    /**
     * <code>repeated sfixed64 row = 1;</code>
     */
    public long getRow(int index) {
      return row_.get(index);
    }
    private int rowMemoizedSerializedSize = -1;

    public static final int COLUMN_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Long> column_;
    /**
     * <code>repeated sfixed64 column = 2;</code>
     */
    public java.util.List<java.lang.Long>
        getColumnList() {
      return column_;
    }
    /**
     * <code>repeated sfixed64 column = 2;</code>
     */
    public int getColumnCount() {
      return column_.size();
    }
    /**
     * <code>repeated sfixed64 column = 2;</code>
     */
    public long getColumn(int index) {
      return column_.get(index);
    }
    private int columnMemoizedSerializedSize = -1;

    public static final int ROWID_FIELD_NUMBER = 3;
    private int rowId_;
    /**
     * <code>int32 rowId = 3;</code>
     */
    public int getRowId() {
      return rowId_;
    }

    public static final int COLUMNID_FIELD_NUMBER = 4;
    private int columnId_;
    /**
     * <code>int32 columnId = 4;</code>
     */
    public int getColumnId() {
      return columnId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getRowList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(rowMemoizedSerializedSize);
      }
      for (int i = 0; i < row_.size(); i++) {
        output.writeSFixed64NoTag(row_.get(i));
      }
      if (getColumnList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(columnMemoizedSerializedSize);
      }
      for (int i = 0; i < column_.size(); i++) {
        output.writeSFixed64NoTag(column_.get(i));
      }
      if (rowId_ != 0) {
        output.writeInt32(3, rowId_);
      }
      if (columnId_ != 0) {
        output.writeInt32(4, columnId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 8 * getRowList().size();
        size += dataSize;
        if (!getRowList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        rowMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        dataSize = 8 * getColumnList().size();
        size += dataSize;
        if (!getColumnList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        columnMemoizedSerializedSize = dataSize;
      }
      if (rowId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, rowId_);
      }
      if (columnId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, columnId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.stubs.matrix.Matrix.multiplyBlockRequest)) {
        return super.equals(obj);
      }
      io.github.stubs.matrix.Matrix.multiplyBlockRequest other = (io.github.stubs.matrix.Matrix.multiplyBlockRequest) obj;

      boolean result = true;
      result = result && getRowList()
          .equals(other.getRowList());
      result = result && getColumnList()
          .equals(other.getColumnList());
      result = result && (getRowId()
          == other.getRowId());
      result = result && (getColumnId()
          == other.getColumnId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRowCount() > 0) {
        hash = (37 * hash) + ROW_FIELD_NUMBER;
        hash = (53 * hash) + getRowList().hashCode();
      }
      if (getColumnCount() > 0) {
        hash = (37 * hash) + COLUMN_FIELD_NUMBER;
        hash = (53 * hash) + getColumnList().hashCode();
      }
      hash = (37 * hash) + ROWID_FIELD_NUMBER;
      hash = (53 * hash) + getRowId();
      hash = (37 * hash) + COLUMNID_FIELD_NUMBER;
      hash = (53 * hash) + getColumnId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.stubs.matrix.Matrix.multiplyBlockRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.stubs.matrix.Matrix.multiplyBlockRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.stubs.matrix.Matrix.multiplyBlockRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.stubs.matrix.Matrix.multiplyBlockRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.stubs.matrix.Matrix.multiplyBlockRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.stubs.matrix.Matrix.multiplyBlockRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.stubs.matrix.Matrix.multiplyBlockRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.stubs.matrix.Matrix.multiplyBlockRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.stubs.matrix.Matrix.multiplyBlockRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.stubs.matrix.Matrix.multiplyBlockRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.stubs.matrix.Matrix.multiplyBlockRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.stubs.matrix.Matrix.multiplyBlockRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.stubs.matrix.Matrix.multiplyBlockRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code multiplyBlockRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:multiplyBlockRequest)
        io.github.stubs.matrix.Matrix.multiplyBlockRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.stubs.matrix.Matrix.internal_static_multiplyBlockRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.stubs.matrix.Matrix.internal_static_multiplyBlockRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.stubs.matrix.Matrix.multiplyBlockRequest.class, io.github.stubs.matrix.Matrix.multiplyBlockRequest.Builder.class);
      }

      // Construct using io.github.stubs.matrix.Matrix.multiplyBlockRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        row_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        column_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        rowId_ = 0;

        columnId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.stubs.matrix.Matrix.internal_static_multiplyBlockRequest_descriptor;
      }

      @java.lang.Override
      public io.github.stubs.matrix.Matrix.multiplyBlockRequest getDefaultInstanceForType() {
        return io.github.stubs.matrix.Matrix.multiplyBlockRequest.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.stubs.matrix.Matrix.multiplyBlockRequest build() {
        io.github.stubs.matrix.Matrix.multiplyBlockRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.stubs.matrix.Matrix.multiplyBlockRequest buildPartial() {
        io.github.stubs.matrix.Matrix.multiplyBlockRequest result = new io.github.stubs.matrix.Matrix.multiplyBlockRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          row_ = java.util.Collections.unmodifiableList(row_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.row_ = row_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          column_ = java.util.Collections.unmodifiableList(column_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.column_ = column_;
        result.rowId_ = rowId_;
        result.columnId_ = columnId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.stubs.matrix.Matrix.multiplyBlockRequest) {
          return mergeFrom((io.github.stubs.matrix.Matrix.multiplyBlockRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.stubs.matrix.Matrix.multiplyBlockRequest other) {
        if (other == io.github.stubs.matrix.Matrix.multiplyBlockRequest.getDefaultInstance()) return this;
        if (!other.row_.isEmpty()) {
          if (row_.isEmpty()) {
            row_ = other.row_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRowIsMutable();
            row_.addAll(other.row_);
          }
          onChanged();
        }
        if (!other.column_.isEmpty()) {
          if (column_.isEmpty()) {
            column_ = other.column_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureColumnIsMutable();
            column_.addAll(other.column_);
          }
          onChanged();
        }
        if (other.getRowId() != 0) {
          setRowId(other.getRowId());
        }
        if (other.getColumnId() != 0) {
          setColumnId(other.getColumnId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.stubs.matrix.Matrix.multiplyBlockRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.stubs.matrix.Matrix.multiplyBlockRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Long> row_ = java.util.Collections.emptyList();
      private void ensureRowIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          row_ = new java.util.ArrayList<java.lang.Long>(row_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated sfixed64 row = 1;</code>
       */
      public java.util.List<java.lang.Long>
          getRowList() {
        return java.util.Collections.unmodifiableList(row_);
      }
      /**
       * <code>repeated sfixed64 row = 1;</code>
       */
      public int getRowCount() {
        return row_.size();
      }
      /**
       * <code>repeated sfixed64 row = 1;</code>
       */
      public long getRow(int index) {
        return row_.get(index);
      }
      /**
       * <code>repeated sfixed64 row = 1;</code>
       */
      public Builder setRow(
          int index, long value) {
        ensureRowIsMutable();
        row_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sfixed64 row = 1;</code>
       */
      public Builder addRow(long value) {
        ensureRowIsMutable();
        row_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sfixed64 row = 1;</code>
       */
      public Builder addAllRow(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureRowIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, row_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sfixed64 row = 1;</code>
       */
      public Builder clearRow() {
        row_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Long> column_ = java.util.Collections.emptyList();
      private void ensureColumnIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          column_ = new java.util.ArrayList<java.lang.Long>(column_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated sfixed64 column = 2;</code>
       */
      public java.util.List<java.lang.Long>
          getColumnList() {
        return java.util.Collections.unmodifiableList(column_);
      }
      /**
       * <code>repeated sfixed64 column = 2;</code>
       */
      public int getColumnCount() {
        return column_.size();
      }
      /**
       * <code>repeated sfixed64 column = 2;</code>
       */
      public long getColumn(int index) {
        return column_.get(index);
      }
      /**
       * <code>repeated sfixed64 column = 2;</code>
       */
      public Builder setColumn(
          int index, long value) {
        ensureColumnIsMutable();
        column_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sfixed64 column = 2;</code>
       */
      public Builder addColumn(long value) {
        ensureColumnIsMutable();
        column_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sfixed64 column = 2;</code>
       */
      public Builder addAllColumn(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureColumnIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, column_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sfixed64 column = 2;</code>
       */
      public Builder clearColumn() {
        column_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private int rowId_ ;
      /**
       * <code>int32 rowId = 3;</code>
       */
      public int getRowId() {
        return rowId_;
      }
      /**
       * <code>int32 rowId = 3;</code>
       */
      public Builder setRowId(int value) {
        
        rowId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 rowId = 3;</code>
       */
      public Builder clearRowId() {
        
        rowId_ = 0;
        onChanged();
        return this;
      }

      private int columnId_ ;
      /**
       * <code>int32 columnId = 4;</code>
       */
      public int getColumnId() {
        return columnId_;
      }
      /**
       * <code>int32 columnId = 4;</code>
       */
      public Builder setColumnId(int value) {
        
        columnId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 columnId = 4;</code>
       */
      public Builder clearColumnId() {
        
        columnId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:multiplyBlockRequest)
    }

    // @@protoc_insertion_point(class_scope:multiplyBlockRequest)
    private static final io.github.stubs.matrix.Matrix.multiplyBlockRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.stubs.matrix.Matrix.multiplyBlockRequest();
    }

    public static io.github.stubs.matrix.Matrix.multiplyBlockRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<multiplyBlockRequest>
        PARSER = new com.google.protobuf.AbstractParser<multiplyBlockRequest>() {
      @java.lang.Override
      public multiplyBlockRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new multiplyBlockRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<multiplyBlockRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<multiplyBlockRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.stubs.matrix.Matrix.multiplyBlockRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface multiplyBlockResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:multiplyBlockResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>sfixed64 element = 1;</code>
     */
    long getElement();

    /**
     * <code>int32 rowId = 2;</code>
     */
    int getRowId();

    /**
     * <code>int32 columnId = 3;</code>
     */
    int getColumnId();
  }
  /**
   * Protobuf type {@code multiplyBlockResponse}
   */
  public  static final class multiplyBlockResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:multiplyBlockResponse)
      multiplyBlockResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use multiplyBlockResponse.newBuilder() to construct.
    private multiplyBlockResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private multiplyBlockResponse() {
      element_ = 0L;
      rowId_ = 0;
      columnId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private multiplyBlockResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              element_ = input.readSFixed64();
              break;
            }
            case 16: {

              rowId_ = input.readInt32();
              break;
            }
            case 24: {

              columnId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.stubs.matrix.Matrix.internal_static_multiplyBlockResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.stubs.matrix.Matrix.internal_static_multiplyBlockResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.stubs.matrix.Matrix.multiplyBlockResponse.class, io.github.stubs.matrix.Matrix.multiplyBlockResponse.Builder.class);
    }

    public static final int ELEMENT_FIELD_NUMBER = 1;
    private long element_;
    /**
     * <code>sfixed64 element = 1;</code>
     */
    public long getElement() {
      return element_;
    }

    public static final int ROWID_FIELD_NUMBER = 2;
    private int rowId_;
    /**
     * <code>int32 rowId = 2;</code>
     */
    public int getRowId() {
      return rowId_;
    }

    public static final int COLUMNID_FIELD_NUMBER = 3;
    private int columnId_;
    /**
     * <code>int32 columnId = 3;</code>
     */
    public int getColumnId() {
      return columnId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (element_ != 0L) {
        output.writeSFixed64(1, element_);
      }
      if (rowId_ != 0) {
        output.writeInt32(2, rowId_);
      }
      if (columnId_ != 0) {
        output.writeInt32(3, columnId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (element_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed64Size(1, element_);
      }
      if (rowId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, rowId_);
      }
      if (columnId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, columnId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.stubs.matrix.Matrix.multiplyBlockResponse)) {
        return super.equals(obj);
      }
      io.github.stubs.matrix.Matrix.multiplyBlockResponse other = (io.github.stubs.matrix.Matrix.multiplyBlockResponse) obj;

      boolean result = true;
      result = result && (getElement()
          == other.getElement());
      result = result && (getRowId()
          == other.getRowId());
      result = result && (getColumnId()
          == other.getColumnId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ELEMENT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getElement());
      hash = (37 * hash) + ROWID_FIELD_NUMBER;
      hash = (53 * hash) + getRowId();
      hash = (37 * hash) + COLUMNID_FIELD_NUMBER;
      hash = (53 * hash) + getColumnId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.stubs.matrix.Matrix.multiplyBlockResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.stubs.matrix.Matrix.multiplyBlockResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.stubs.matrix.Matrix.multiplyBlockResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.stubs.matrix.Matrix.multiplyBlockResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.stubs.matrix.Matrix.multiplyBlockResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.stubs.matrix.Matrix.multiplyBlockResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.stubs.matrix.Matrix.multiplyBlockResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.stubs.matrix.Matrix.multiplyBlockResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.stubs.matrix.Matrix.multiplyBlockResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.stubs.matrix.Matrix.multiplyBlockResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.stubs.matrix.Matrix.multiplyBlockResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.stubs.matrix.Matrix.multiplyBlockResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.stubs.matrix.Matrix.multiplyBlockResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code multiplyBlockResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:multiplyBlockResponse)
        io.github.stubs.matrix.Matrix.multiplyBlockResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.stubs.matrix.Matrix.internal_static_multiplyBlockResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.stubs.matrix.Matrix.internal_static_multiplyBlockResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.stubs.matrix.Matrix.multiplyBlockResponse.class, io.github.stubs.matrix.Matrix.multiplyBlockResponse.Builder.class);
      }

      // Construct using io.github.stubs.matrix.Matrix.multiplyBlockResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        element_ = 0L;

        rowId_ = 0;

        columnId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.stubs.matrix.Matrix.internal_static_multiplyBlockResponse_descriptor;
      }

      @java.lang.Override
      public io.github.stubs.matrix.Matrix.multiplyBlockResponse getDefaultInstanceForType() {
        return io.github.stubs.matrix.Matrix.multiplyBlockResponse.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.stubs.matrix.Matrix.multiplyBlockResponse build() {
        io.github.stubs.matrix.Matrix.multiplyBlockResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.stubs.matrix.Matrix.multiplyBlockResponse buildPartial() {
        io.github.stubs.matrix.Matrix.multiplyBlockResponse result = new io.github.stubs.matrix.Matrix.multiplyBlockResponse(this);
        result.element_ = element_;
        result.rowId_ = rowId_;
        result.columnId_ = columnId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.stubs.matrix.Matrix.multiplyBlockResponse) {
          return mergeFrom((io.github.stubs.matrix.Matrix.multiplyBlockResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.stubs.matrix.Matrix.multiplyBlockResponse other) {
        if (other == io.github.stubs.matrix.Matrix.multiplyBlockResponse.getDefaultInstance()) return this;
        if (other.getElement() != 0L) {
          setElement(other.getElement());
        }
        if (other.getRowId() != 0) {
          setRowId(other.getRowId());
        }
        if (other.getColumnId() != 0) {
          setColumnId(other.getColumnId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.stubs.matrix.Matrix.multiplyBlockResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.stubs.matrix.Matrix.multiplyBlockResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long element_ ;
      /**
       * <code>sfixed64 element = 1;</code>
       */
      public long getElement() {
        return element_;
      }
      /**
       * <code>sfixed64 element = 1;</code>
       */
      public Builder setElement(long value) {
        
        element_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sfixed64 element = 1;</code>
       */
      public Builder clearElement() {
        
        element_ = 0L;
        onChanged();
        return this;
      }

      private int rowId_ ;
      /**
       * <code>int32 rowId = 2;</code>
       */
      public int getRowId() {
        return rowId_;
      }
      /**
       * <code>int32 rowId = 2;</code>
       */
      public Builder setRowId(int value) {
        
        rowId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 rowId = 2;</code>
       */
      public Builder clearRowId() {
        
        rowId_ = 0;
        onChanged();
        return this;
      }

      private int columnId_ ;
      /**
       * <code>int32 columnId = 3;</code>
       */
      public int getColumnId() {
        return columnId_;
      }
      /**
       * <code>int32 columnId = 3;</code>
       */
      public Builder setColumnId(int value) {
        
        columnId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 columnId = 3;</code>
       */
      public Builder clearColumnId() {
        
        columnId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:multiplyBlockResponse)
    }

    // @@protoc_insertion_point(class_scope:multiplyBlockResponse)
    private static final io.github.stubs.matrix.Matrix.multiplyBlockResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.stubs.matrix.Matrix.multiplyBlockResponse();
    }

    public static io.github.stubs.matrix.Matrix.multiplyBlockResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<multiplyBlockResponse>
        PARSER = new com.google.protobuf.AbstractParser<multiplyBlockResponse>() {
      @java.lang.Override
      public multiplyBlockResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new multiplyBlockResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<multiplyBlockResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<multiplyBlockResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.stubs.matrix.Matrix.multiplyBlockResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_multiplyBlockRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_multiplyBlockRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_multiplyBlockResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_multiplyBlockResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014matrix.proto\"T\n\024multiplyBlockRequest\022\013" +
      "\n\003row\030\001 \003(\020\022\016\n\006column\030\002 \003(\020\022\r\n\005rowId\030\003 \001" +
      "(\005\022\020\n\010columnId\030\004 \001(\005\"I\n\025multiplyBlockRes" +
      "ponse\022\017\n\007element\030\001 \001(\020\022\r\n\005rowId\030\002 \001(\005\022\020\n" +
      "\010columnId\030\003 \001(\0052O\n\007compute\022D\n\023multiplyRo" +
      "wByColumn\022\025.multiplyBlockRequest\032\026.multi" +
      "plyBlockResponseB\030\n\026io.github.stubs.matr" +
      "ixb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_multiplyBlockRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_multiplyBlockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_multiplyBlockRequest_descriptor,
        new java.lang.String[] { "Row", "Column", "RowId", "ColumnId", });
    internal_static_multiplyBlockResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_multiplyBlockResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_multiplyBlockResponse_descriptor,
        new java.lang.String[] { "Element", "RowId", "ColumnId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
