// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file.proto

package io.github.stubs.file;

public final class FileOuterClass {
  private FileOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UploadFileRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UploadFileRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ImageInfo info = 1;</code>
     */
    boolean hasInfo();
    /**
     * <code>.ImageInfo info = 1;</code>
     */
    io.github.stubs.file.FileOuterClass.ImageInfo getInfo();
    /**
     * <code>.ImageInfo info = 1;</code>
     */
    io.github.stubs.file.FileOuterClass.ImageInfoOrBuilder getInfoOrBuilder();

    /**
     * <code>bytes chunkData = 2;</code>
     */
    com.google.protobuf.ByteString getChunkData();

    public io.github.stubs.file.FileOuterClass.UploadFileRequest.DataCase getDataCase();
  }
  /**
   * Protobuf type {@code UploadFileRequest}
   */
  public  static final class UploadFileRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UploadFileRequest)
      UploadFileRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UploadFileRequest.newBuilder() to construct.
    private UploadFileRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UploadFileRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UploadFileRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.github.stubs.file.FileOuterClass.ImageInfo.Builder subBuilder = null;
              if (dataCase_ == 1) {
                subBuilder = ((io.github.stubs.file.FileOuterClass.ImageInfo) data_).toBuilder();
              }
              data_ =
                  input.readMessage(io.github.stubs.file.FileOuterClass.ImageInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((io.github.stubs.file.FileOuterClass.ImageInfo) data_);
                data_ = subBuilder.buildPartial();
              }
              dataCase_ = 1;
              break;
            }
            case 18: {
              dataCase_ = 2;
              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.stubs.file.FileOuterClass.internal_static_UploadFileRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.stubs.file.FileOuterClass.internal_static_UploadFileRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.stubs.file.FileOuterClass.UploadFileRequest.class, io.github.stubs.file.FileOuterClass.UploadFileRequest.Builder.class);
    }

    private int dataCase_ = 0;
    private java.lang.Object data_;
    public enum DataCase
        implements com.google.protobuf.Internal.EnumLite {
      INFO(1),
      CHUNKDATA(2),
      DATA_NOT_SET(0);
      private final int value;
      private DataCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataCase forNumber(int value) {
        switch (value) {
          case 1: return INFO;
          case 2: return CHUNKDATA;
          case 0: return DATA_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataCase
    getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public static final int INFO_FIELD_NUMBER = 1;
    /**
     * <code>.ImageInfo info = 1;</code>
     */
    public boolean hasInfo() {
      return dataCase_ == 1;
    }
    /**
     * <code>.ImageInfo info = 1;</code>
     */
    public io.github.stubs.file.FileOuterClass.ImageInfo getInfo() {
      if (dataCase_ == 1) {
         return (io.github.stubs.file.FileOuterClass.ImageInfo) data_;
      }
      return io.github.stubs.file.FileOuterClass.ImageInfo.getDefaultInstance();
    }
    /**
     * <code>.ImageInfo info = 1;</code>
     */
    public io.github.stubs.file.FileOuterClass.ImageInfoOrBuilder getInfoOrBuilder() {
      if (dataCase_ == 1) {
         return (io.github.stubs.file.FileOuterClass.ImageInfo) data_;
      }
      return io.github.stubs.file.FileOuterClass.ImageInfo.getDefaultInstance();
    }

    public static final int CHUNKDATA_FIELD_NUMBER = 2;
    /**
     * <code>bytes chunkData = 2;</code>
     */
    public com.google.protobuf.ByteString getChunkData() {
      if (dataCase_ == 2) {
        return (com.google.protobuf.ByteString) data_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataCase_ == 1) {
        output.writeMessage(1, (io.github.stubs.file.FileOuterClass.ImageInfo) data_);
      }
      if (dataCase_ == 2) {
        output.writeBytes(
            2, (com.google.protobuf.ByteString) data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (io.github.stubs.file.FileOuterClass.ImageInfo) data_);
      }
      if (dataCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
              2, (com.google.protobuf.ByteString) data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.stubs.file.FileOuterClass.UploadFileRequest)) {
        return super.equals(obj);
      }
      io.github.stubs.file.FileOuterClass.UploadFileRequest other = (io.github.stubs.file.FileOuterClass.UploadFileRequest) obj;

      boolean result = true;
      result = result && getDataCase().equals(
          other.getDataCase());
      if (!result) return false;
      switch (dataCase_) {
        case 1:
          result = result && getInfo()
              .equals(other.getInfo());
          break;
        case 2:
          result = result && getChunkData()
              .equals(other.getChunkData());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (dataCase_) {
        case 1:
          hash = (37 * hash) + INFO_FIELD_NUMBER;
          hash = (53 * hash) + getInfo().hashCode();
          break;
        case 2:
          hash = (37 * hash) + CHUNKDATA_FIELD_NUMBER;
          hash = (53 * hash) + getChunkData().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.stubs.file.FileOuterClass.UploadFileRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.stubs.file.FileOuterClass.UploadFileRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.stubs.file.FileOuterClass.UploadFileRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.stubs.file.FileOuterClass.UploadFileRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.stubs.file.FileOuterClass.UploadFileRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.stubs.file.FileOuterClass.UploadFileRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.stubs.file.FileOuterClass.UploadFileRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.stubs.file.FileOuterClass.UploadFileRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.stubs.file.FileOuterClass.UploadFileRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.stubs.file.FileOuterClass.UploadFileRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.stubs.file.FileOuterClass.UploadFileRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.stubs.file.FileOuterClass.UploadFileRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.stubs.file.FileOuterClass.UploadFileRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UploadFileRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UploadFileRequest)
        io.github.stubs.file.FileOuterClass.UploadFileRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.stubs.file.FileOuterClass.internal_static_UploadFileRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.stubs.file.FileOuterClass.internal_static_UploadFileRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.stubs.file.FileOuterClass.UploadFileRequest.class, io.github.stubs.file.FileOuterClass.UploadFileRequest.Builder.class);
      }

      // Construct using io.github.stubs.file.FileOuterClass.UploadFileRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataCase_ = 0;
        data_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.stubs.file.FileOuterClass.internal_static_UploadFileRequest_descriptor;
      }

      @java.lang.Override
      public io.github.stubs.file.FileOuterClass.UploadFileRequest getDefaultInstanceForType() {
        return io.github.stubs.file.FileOuterClass.UploadFileRequest.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.stubs.file.FileOuterClass.UploadFileRequest build() {
        io.github.stubs.file.FileOuterClass.UploadFileRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.stubs.file.FileOuterClass.UploadFileRequest buildPartial() {
        io.github.stubs.file.FileOuterClass.UploadFileRequest result = new io.github.stubs.file.FileOuterClass.UploadFileRequest(this);
        if (dataCase_ == 1) {
          if (infoBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = infoBuilder_.build();
          }
        }
        if (dataCase_ == 2) {
          result.data_ = data_;
        }
        result.dataCase_ = dataCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.stubs.file.FileOuterClass.UploadFileRequest) {
          return mergeFrom((io.github.stubs.file.FileOuterClass.UploadFileRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.stubs.file.FileOuterClass.UploadFileRequest other) {
        if (other == io.github.stubs.file.FileOuterClass.UploadFileRequest.getDefaultInstance()) return this;
        switch (other.getDataCase()) {
          case INFO: {
            mergeInfo(other.getInfo());
            break;
          }
          case CHUNKDATA: {
            setChunkData(other.getChunkData());
            break;
          }
          case DATA_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.stubs.file.FileOuterClass.UploadFileRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.stubs.file.FileOuterClass.UploadFileRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataCase_ = 0;
      private java.lang.Object data_;
      public DataCase
          getDataCase() {
        return DataCase.forNumber(
            dataCase_);
      }

      public Builder clearData() {
        dataCase_ = 0;
        data_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.stubs.file.FileOuterClass.ImageInfo, io.github.stubs.file.FileOuterClass.ImageInfo.Builder, io.github.stubs.file.FileOuterClass.ImageInfoOrBuilder> infoBuilder_;
      /**
       * <code>.ImageInfo info = 1;</code>
       */
      public boolean hasInfo() {
        return dataCase_ == 1;
      }
      /**
       * <code>.ImageInfo info = 1;</code>
       */
      public io.github.stubs.file.FileOuterClass.ImageInfo getInfo() {
        if (infoBuilder_ == null) {
          if (dataCase_ == 1) {
            return (io.github.stubs.file.FileOuterClass.ImageInfo) data_;
          }
          return io.github.stubs.file.FileOuterClass.ImageInfo.getDefaultInstance();
        } else {
          if (dataCase_ == 1) {
            return infoBuilder_.getMessage();
          }
          return io.github.stubs.file.FileOuterClass.ImageInfo.getDefaultInstance();
        }
      }
      /**
       * <code>.ImageInfo info = 1;</code>
       */
      public Builder setInfo(io.github.stubs.file.FileOuterClass.ImageInfo value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          infoBuilder_.setMessage(value);
        }
        dataCase_ = 1;
        return this;
      }
      /**
       * <code>.ImageInfo info = 1;</code>
       */
      public Builder setInfo(
          io.github.stubs.file.FileOuterClass.ImageInfo.Builder builderForValue) {
        if (infoBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          infoBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 1;
        return this;
      }
      /**
       * <code>.ImageInfo info = 1;</code>
       */
      public Builder mergeInfo(io.github.stubs.file.FileOuterClass.ImageInfo value) {
        if (infoBuilder_ == null) {
          if (dataCase_ == 1 &&
              data_ != io.github.stubs.file.FileOuterClass.ImageInfo.getDefaultInstance()) {
            data_ = io.github.stubs.file.FileOuterClass.ImageInfo.newBuilder((io.github.stubs.file.FileOuterClass.ImageInfo) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 1) {
            infoBuilder_.mergeFrom(value);
          }
          infoBuilder_.setMessage(value);
        }
        dataCase_ = 1;
        return this;
      }
      /**
       * <code>.ImageInfo info = 1;</code>
       */
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          if (dataCase_ == 1) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 1) {
            dataCase_ = 0;
            data_ = null;
          }
          infoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.ImageInfo info = 1;</code>
       */
      public io.github.stubs.file.FileOuterClass.ImageInfo.Builder getInfoBuilder() {
        return getInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.ImageInfo info = 1;</code>
       */
      public io.github.stubs.file.FileOuterClass.ImageInfoOrBuilder getInfoOrBuilder() {
        if ((dataCase_ == 1) && (infoBuilder_ != null)) {
          return infoBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 1) {
            return (io.github.stubs.file.FileOuterClass.ImageInfo) data_;
          }
          return io.github.stubs.file.FileOuterClass.ImageInfo.getDefaultInstance();
        }
      }
      /**
       * <code>.ImageInfo info = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.stubs.file.FileOuterClass.ImageInfo, io.github.stubs.file.FileOuterClass.ImageInfo.Builder, io.github.stubs.file.FileOuterClass.ImageInfoOrBuilder> 
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          if (!(dataCase_ == 1)) {
            data_ = io.github.stubs.file.FileOuterClass.ImageInfo.getDefaultInstance();
          }
          infoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.github.stubs.file.FileOuterClass.ImageInfo, io.github.stubs.file.FileOuterClass.ImageInfo.Builder, io.github.stubs.file.FileOuterClass.ImageInfoOrBuilder>(
                  (io.github.stubs.file.FileOuterClass.ImageInfo) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 1;
        onChanged();;
        return infoBuilder_;
      }

      /**
       * <code>bytes chunkData = 2;</code>
       */
      public com.google.protobuf.ByteString getChunkData() {
        if (dataCase_ == 2) {
          return (com.google.protobuf.ByteString) data_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }
      /**
       * <code>bytes chunkData = 2;</code>
       */
      public Builder setChunkData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  dataCase_ = 2;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes chunkData = 2;</code>
       */
      public Builder clearChunkData() {
        if (dataCase_ == 2) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UploadFileRequest)
    }

    // @@protoc_insertion_point(class_scope:UploadFileRequest)
    private static final io.github.stubs.file.FileOuterClass.UploadFileRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.stubs.file.FileOuterClass.UploadFileRequest();
    }

    public static io.github.stubs.file.FileOuterClass.UploadFileRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UploadFileRequest>
        PARSER = new com.google.protobuf.AbstractParser<UploadFileRequest>() {
      @java.lang.Override
      public UploadFileRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UploadFileRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UploadFileRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UploadFileRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.stubs.file.FileOuterClass.UploadFileRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ImageInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ImageInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string fileId = 1;</code>
     */
    java.lang.String getFileId();
    /**
     * <code>string fileId = 1;</code>
     */
    com.google.protobuf.ByteString
        getFileIdBytes();

    /**
     * <code>string fileType = 2;</code>
     */
    java.lang.String getFileType();
    /**
     * <code>string fileType = 2;</code>
     */
    com.google.protobuf.ByteString
        getFileTypeBytes();
  }
  /**
   * Protobuf type {@code ImageInfo}
   */
  public  static final class ImageInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ImageInfo)
      ImageInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ImageInfo.newBuilder() to construct.
    private ImageInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ImageInfo() {
      fileId_ = "";
      fileType_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ImageInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              fileId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              fileType_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.stubs.file.FileOuterClass.internal_static_ImageInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.stubs.file.FileOuterClass.internal_static_ImageInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.stubs.file.FileOuterClass.ImageInfo.class, io.github.stubs.file.FileOuterClass.ImageInfo.Builder.class);
    }

    public static final int FILEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object fileId_;
    /**
     * <code>string fileId = 1;</code>
     */
    public java.lang.String getFileId() {
      java.lang.Object ref = fileId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileId_ = s;
        return s;
      }
    }
    /**
     * <code>string fileId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFileIdBytes() {
      java.lang.Object ref = fileId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILETYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object fileType_;
    /**
     * <code>string fileType = 2;</code>
     */
    public java.lang.String getFileType() {
      java.lang.Object ref = fileType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileType_ = s;
        return s;
      }
    }
    /**
     * <code>string fileType = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFileTypeBytes() {
      java.lang.Object ref = fileType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFileIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileId_);
      }
      if (!getFileTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fileType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFileIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileId_);
      }
      if (!getFileTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fileType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.stubs.file.FileOuterClass.ImageInfo)) {
        return super.equals(obj);
      }
      io.github.stubs.file.FileOuterClass.ImageInfo other = (io.github.stubs.file.FileOuterClass.ImageInfo) obj;

      boolean result = true;
      result = result && getFileId()
          .equals(other.getFileId());
      result = result && getFileType()
          .equals(other.getFileType());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILEID_FIELD_NUMBER;
      hash = (53 * hash) + getFileId().hashCode();
      hash = (37 * hash) + FILETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getFileType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.stubs.file.FileOuterClass.ImageInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.stubs.file.FileOuterClass.ImageInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.stubs.file.FileOuterClass.ImageInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.stubs.file.FileOuterClass.ImageInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.stubs.file.FileOuterClass.ImageInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.stubs.file.FileOuterClass.ImageInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.stubs.file.FileOuterClass.ImageInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.stubs.file.FileOuterClass.ImageInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.stubs.file.FileOuterClass.ImageInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.stubs.file.FileOuterClass.ImageInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.stubs.file.FileOuterClass.ImageInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.stubs.file.FileOuterClass.ImageInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.stubs.file.FileOuterClass.ImageInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ImageInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ImageInfo)
        io.github.stubs.file.FileOuterClass.ImageInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.stubs.file.FileOuterClass.internal_static_ImageInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.stubs.file.FileOuterClass.internal_static_ImageInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.stubs.file.FileOuterClass.ImageInfo.class, io.github.stubs.file.FileOuterClass.ImageInfo.Builder.class);
      }

      // Construct using io.github.stubs.file.FileOuterClass.ImageInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fileId_ = "";

        fileType_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.stubs.file.FileOuterClass.internal_static_ImageInfo_descriptor;
      }

      @java.lang.Override
      public io.github.stubs.file.FileOuterClass.ImageInfo getDefaultInstanceForType() {
        return io.github.stubs.file.FileOuterClass.ImageInfo.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.stubs.file.FileOuterClass.ImageInfo build() {
        io.github.stubs.file.FileOuterClass.ImageInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.stubs.file.FileOuterClass.ImageInfo buildPartial() {
        io.github.stubs.file.FileOuterClass.ImageInfo result = new io.github.stubs.file.FileOuterClass.ImageInfo(this);
        result.fileId_ = fileId_;
        result.fileType_ = fileType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.stubs.file.FileOuterClass.ImageInfo) {
          return mergeFrom((io.github.stubs.file.FileOuterClass.ImageInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.stubs.file.FileOuterClass.ImageInfo other) {
        if (other == io.github.stubs.file.FileOuterClass.ImageInfo.getDefaultInstance()) return this;
        if (!other.getFileId().isEmpty()) {
          fileId_ = other.fileId_;
          onChanged();
        }
        if (!other.getFileType().isEmpty()) {
          fileType_ = other.fileType_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.stubs.file.FileOuterClass.ImageInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.stubs.file.FileOuterClass.ImageInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object fileId_ = "";
      /**
       * <code>string fileId = 1;</code>
       */
      public java.lang.String getFileId() {
        java.lang.Object ref = fileId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fileId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFileIdBytes() {
        java.lang.Object ref = fileId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fileId = 1;</code>
       */
      public Builder setFileId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fileId = 1;</code>
       */
      public Builder clearFileId() {
        
        fileId_ = getDefaultInstance().getFileId();
        onChanged();
        return this;
      }
      /**
       * <code>string fileId = 1;</code>
       */
      public Builder setFileIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fileType_ = "";
      /**
       * <code>string fileType = 2;</code>
       */
      public java.lang.String getFileType() {
        java.lang.Object ref = fileType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fileType = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFileTypeBytes() {
        java.lang.Object ref = fileType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fileType = 2;</code>
       */
      public Builder setFileType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fileType = 2;</code>
       */
      public Builder clearFileType() {
        
        fileType_ = getDefaultInstance().getFileType();
        onChanged();
        return this;
      }
      /**
       * <code>string fileType = 2;</code>
       */
      public Builder setFileTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileType_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ImageInfo)
    }

    // @@protoc_insertion_point(class_scope:ImageInfo)
    private static final io.github.stubs.file.FileOuterClass.ImageInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.stubs.file.FileOuterClass.ImageInfo();
    }

    public static io.github.stubs.file.FileOuterClass.ImageInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ImageInfo>
        PARSER = new com.google.protobuf.AbstractParser<ImageInfo>() {
      @java.lang.Override
      public ImageInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ImageInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ImageInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImageInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.stubs.file.FileOuterClass.ImageInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UploadFileResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UploadFileResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>uint32 size = 2;</code>
     */
    int getSize();
  }
  /**
   * Protobuf type {@code UploadFileResponse}
   */
  public  static final class UploadFileResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UploadFileResponse)
      UploadFileResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UploadFileResponse.newBuilder() to construct.
    private UploadFileResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UploadFileResponse() {
      id_ = "";
      size_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UploadFileResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 16: {

              size_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.stubs.file.FileOuterClass.internal_static_UploadFileResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.stubs.file.FileOuterClass.internal_static_UploadFileResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.stubs.file.FileOuterClass.UploadFileResponse.class, io.github.stubs.file.FileOuterClass.UploadFileResponse.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIZE_FIELD_NUMBER = 2;
    private int size_;
    /**
     * <code>uint32 size = 2;</code>
     */
    public int getSize() {
      return size_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (size_ != 0) {
        output.writeUInt32(2, size_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (size_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, size_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.stubs.file.FileOuterClass.UploadFileResponse)) {
        return super.equals(obj);
      }
      io.github.stubs.file.FileOuterClass.UploadFileResponse other = (io.github.stubs.file.FileOuterClass.UploadFileResponse) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && (getSize()
          == other.getSize());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSize();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.stubs.file.FileOuterClass.UploadFileResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.stubs.file.FileOuterClass.UploadFileResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.stubs.file.FileOuterClass.UploadFileResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.stubs.file.FileOuterClass.UploadFileResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.stubs.file.FileOuterClass.UploadFileResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.stubs.file.FileOuterClass.UploadFileResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.stubs.file.FileOuterClass.UploadFileResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.stubs.file.FileOuterClass.UploadFileResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.stubs.file.FileOuterClass.UploadFileResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.stubs.file.FileOuterClass.UploadFileResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.stubs.file.FileOuterClass.UploadFileResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.stubs.file.FileOuterClass.UploadFileResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.stubs.file.FileOuterClass.UploadFileResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UploadFileResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UploadFileResponse)
        io.github.stubs.file.FileOuterClass.UploadFileResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.stubs.file.FileOuterClass.internal_static_UploadFileResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.stubs.file.FileOuterClass.internal_static_UploadFileResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.stubs.file.FileOuterClass.UploadFileResponse.class, io.github.stubs.file.FileOuterClass.UploadFileResponse.Builder.class);
      }

      // Construct using io.github.stubs.file.FileOuterClass.UploadFileResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        size_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.stubs.file.FileOuterClass.internal_static_UploadFileResponse_descriptor;
      }

      @java.lang.Override
      public io.github.stubs.file.FileOuterClass.UploadFileResponse getDefaultInstanceForType() {
        return io.github.stubs.file.FileOuterClass.UploadFileResponse.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.stubs.file.FileOuterClass.UploadFileResponse build() {
        io.github.stubs.file.FileOuterClass.UploadFileResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.stubs.file.FileOuterClass.UploadFileResponse buildPartial() {
        io.github.stubs.file.FileOuterClass.UploadFileResponse result = new io.github.stubs.file.FileOuterClass.UploadFileResponse(this);
        result.id_ = id_;
        result.size_ = size_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.stubs.file.FileOuterClass.UploadFileResponse) {
          return mergeFrom((io.github.stubs.file.FileOuterClass.UploadFileResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.stubs.file.FileOuterClass.UploadFileResponse other) {
        if (other == io.github.stubs.file.FileOuterClass.UploadFileResponse.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getSize() != 0) {
          setSize(other.getSize());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.stubs.file.FileOuterClass.UploadFileResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.stubs.file.FileOuterClass.UploadFileResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private int size_ ;
      /**
       * <code>uint32 size = 2;</code>
       */
      public int getSize() {
        return size_;
      }
      /**
       * <code>uint32 size = 2;</code>
       */
      public Builder setSize(int value) {
        
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 size = 2;</code>
       */
      public Builder clearSize() {
        
        size_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UploadFileResponse)
    }

    // @@protoc_insertion_point(class_scope:UploadFileResponse)
    private static final io.github.stubs.file.FileOuterClass.UploadFileResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.stubs.file.FileOuterClass.UploadFileResponse();
    }

    public static io.github.stubs.file.FileOuterClass.UploadFileResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UploadFileResponse>
        PARSER = new com.google.protobuf.AbstractParser<UploadFileResponse>() {
      @java.lang.Override
      public UploadFileResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UploadFileResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UploadFileResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UploadFileResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.stubs.file.FileOuterClass.UploadFileResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UploadFileRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UploadFileRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImageInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImageInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UploadFileResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UploadFileResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nfile.proto\"L\n\021UploadFileRequest\022\032\n\004inf" +
      "o\030\001 \001(\0132\n.ImageInfoH\000\022\023\n\tchunkData\030\002 \001(\014" +
      "H\000B\006\n\004data\"-\n\tImageInfo\022\016\n\006fileId\030\001 \001(\t\022" +
      "\020\n\010fileType\030\002 \001(\t\".\n\022UploadFileResponse\022" +
      "\n\n\002id\030\001 \001(\t\022\014\n\004size\030\002 \001(\r2B\n\004File\022:\n\013Upl" +
      "oadImage\022\022.UploadFileRequest\032\023.UploadFil" +
      "eResponse\"\000(\001B\026\n\024io.github.stubs.fileb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_UploadFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UploadFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UploadFileRequest_descriptor,
        new java.lang.String[] { "Info", "ChunkData", "Data", });
    internal_static_ImageInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ImageInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImageInfo_descriptor,
        new java.lang.String[] { "FileId", "FileType", });
    internal_static_UploadFileResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UploadFileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UploadFileResponse_descriptor,
        new java.lang.String[] { "Id", "Size", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
